---
# # Un playbook commence généralement par '---', ce qui indique le début d'un document YAML.
# # Nom du playbook : Une description courte et significative de ce que fait le playbook.
# - name: playbook-exemple
#   # Les hôtes sur lesquels le playbook sera exécuté. 
#   # Cela peut être un nom d'hôte, un groupe d'hôtes ou 'all' pour tous les hôtes.
#   hosts: target1
#   # Utiliser les privilèges d'administrateur pour exécuter les tâches. 
#   # Si 'true', Ansible utilisera sudo (ou un mécanisme similaire) pour exécuter les commandes.
#   become: true/false
#   # Liste des tâches à exécuter. 
#   # Chaque tâche est une action que Ansible effectuera sur les hôtes cibles.
#   tasks:
#     # Description de la tâche.
#     - name: Description de la tâche 1
#       module_ansible: # Nom du module Ansible utilisé pour cette tâche.
#         paramètre_1: valeur
#         paramètre_2: "{{ nom_variable_1 }}" # Utilisation d'une variable dans un paramètre.
#     # Une autre tâche.
#     - name: Description de la tâche 2
#       autre_module_ansible:
#         paramètre_1: valeur
#   # Gestionnaires : actions à exécuter en réponse à des notifications des tâches.
#   # Par exemple, si un fichier de configuration est modifié, un service peut avoir besoin d'être rechargé.

- name: playbook-exemple
  hosts: target  # Le groupe d'hôtes cible
  become: yes  # Utiliser sudo pour exécuter les commandes en tant qu'administrateur

  tasks:
    - name: Installer les dépendances pour compiler NodeJs
      ansible.builtin.yum: #(équivalent yum)
        name: ["gcc-c++", "make"]
        state: present  

    - name: Installer Node.js
      yum:
        name: nodejs
        state: present

    - name: Installer gatsby-cli
      npm:
        name: gatsby-cli
        global: yes 
  
    - name: Créer un nouveau projet Gatsby
      command: gatsby new ansible-projet --skip-git
      args:
        chdir: /ansible


    - name: Installer Apache
      package:
        name: httpd  # Nom du package Apache sur certaines distributions
        state: present